### ISSUE TITLE
segmentation fault on array initialization, when array of size 9 or more

### ISSUE THREAD

**Issue by lilith218** [MPI-SWS/genmc#27]
The following code causes segmentation fault
```
#include <stdio.h>
int
main(void)
{
    char buff[9] = {'a'};
}
```
**core-dump**
```
#0  0x00007f72c8d30d62 in llvm::PointerType::get(llvm::Type*, unsigned int) () from /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1
#1  0x00007f72c8c52d9a in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1
#2  0x00007f72c8c51ba1 in llvm::ConstantFoldGetElementPtr(llvm::Type*, llvm::Constant*, bool, llvm::Optional<unsigned int>, llvm::ArrayRef<llvm::Value*>) () from /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1
#3  0x00007f72c8c6809e in llvm::ConstantExpr::getGetElementPtr(llvm::Type*, llvm::Constant*, llvm::ArrayRef<llvm::Value*>, bool, llvm::Optional<unsigned int>, llvm::Type*) () from /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1
#4  0x000055f5ec5fc504 in llvm::ConstantExpr::getInBoundsGetElementPtr (IdxList=..., C=0x55f5ee0a7c58, Ty=0x0) at /usr/lib/llvm-8/include/llvm/IR/Constants.h:1194
#5  llvm::ConstantFolder::CreateInBoundsGetElementPtr (IdxList=..., C=0x55f5ee0a7c58, Ty=0x0, this=0x7fff9daca9a0) at /usr/lib/llvm-8/include/llvm/IR/ConstantFolder.h:174
#6  llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>::CreateInBoundsGEP (this=this@entry=0x7fff9daca960, Ty=Ty@entry=0x0, Ptr=0x55f5ee0a7c58, IdxList=..., Name=...) at /usr/lib/llvm-8/include/llvm/IR/IRBuilder.h:1491
#7  0x000055f5ec5fae22 in promoteMemCpy (builder=..., dst=0x55f5ee0a15d8, src=<optimized out>, args=std::vector of length 2, capacity 2 = {...}, typ=0x55f5ee00eb08) at /usr/include/c++/10/bits/stl_vector.h:918
#8  0x000055f5ec5fba20 in promoteMemIntrinsic<PromoteMemIntrinsicPass::tryPromoteMemCpy(llvm::MemCpyInst*, llvm::Module&)::<lambda(llvm::Type*, const std::vector<llvm::Value*, std::allocator<llvm::Value*> >&)> >(llvm::Type *, std::vector<llvm::Value*, std::allocator<llvm::Value*> > &, struct {...} &&) (typ=0x55f5ee026c10, args=std::vector of length 2, capacity 2 = {...}, promoteFun=...) at /usr/lib/llvm-8/include/llvm/IR/DerivedTypes.h:360
#9  0x000055f5ec5fbda3 in PromoteMemIntrinsicPass::tryPromoteMemCpy (this=this@entry=0x55f5ee0acb20, MI=MI@entry=0x55f5ee0a82f8, M=...) at /usr/lib/llvm-8/include/llvm/IR/DerivedTypes.h:486
#10 0x000055f5ec5fc051 in PromoteMemIntrinsicPass::tryPromoteMemCpy (M=..., MI=0x55f5ee0a82f8, this=0x55f5ee0acb20) at PromoteMemIntrinsicPass.cpp:139
#11 PromoteMemIntrinsicPass::runOnModule (M=..., this=0x55f5ee0acb20) at PromoteMemIntrinsicPass.cpp:215
#12 PromoteMemIntrinsicPass::runOnModule (this=0x55f5ee0acb20, M=...) at PromoteMemIntrinsicPass.cpp:203
#13 0x00007f72c8cf5b4e in llvm::legacy::PassManagerImpl::run(llvm::Module&) () from /usr/lib/x86_64-linux-gnu/libLLVM-8.so.1
#14 0x000055f5ec5e4c8c in LLVMModule::transformLLVMModule (mod=..., conf=0x55f5ee00d5e0, MI=...) at LLVMModule.cpp:131
#15 0x000055f5ec5b49a0 in GenMCDriver::GenMCDriver (this=0x55f5ee09f640, conf=..., mod=std::unique_ptr<llvm::Module> = {...}, start=<optimized out>) at /usr/include/c++/10/bits/unique_ptr.h:173
#16 0x000055f5ec60463d in RC11Driver::RC11Driver (this=0x55f5ee09f640, conf=..., mod=..., start=<optimized out>) at /usr/include/c++/10/bits/unique_ptr.h:172
#17 0x000055f5ec598d4d in DriverFactory::create (conf=std::unique_ptr<Config> = {...}, mod=std::unique_ptr<llvm::Module> = {...}, start=start@entry=18427) at DriverFactory.cpp:32
#18 0x000055f5ec58aed2 in main (argc=<optimized out>, argv=0x7fff9dacd0f8) at /usr/include/c++/10/bits/unique_ptr.h:172
```

If I move the array declaration outside the main function 
```
#include <stdio.h>

char buff[9] = {'a'};
int
main(void)
{
    return 0;
}
```
I get the following output:
```
WARNING: Inadequate naming info for variable buff.
Please submit a bug report to michalis@mpi-sws.org
Number of complete executions explored: 1
Total wall-clock time: 0.01s
```

**Comment by michaliskok** [comment]
Should be fixed in v0.7.
