### ISSUE TITLE
GenMC crashes if built against assertions-enabled LLVM

### ISSUE THREAD

**Issue by margnus1** [MPI-SWS/genmc#28]
It seems like GenMC crashes when it's compiled against an assertions-enabled build of LLVM with the following message:
```
genmc: /home/magnus/repos/llvm-monorepo/llvm/lib/Support/CommandLine.cpp:1344: bool {anonymous}::CommandLineParser::ParseCommandLineOptions(int, const char* const*, llvm::StringRef, llvm::raw_ostream*, bool): Assertion `hasOptions() && "No options specified!"' failed.
```

This happens with all the different LLVM versions I have lying around, but this particular one is configured with the following cmake flags, in case it helps with reproduction `-DLLVM_OPTIMIZED_TABLEGEN=y -DLLVM_LINK_LLVM_DYLIB=y -DLLVM_USE_SPLIT_DWARF=y -DLLVM_TARGETS_TO_BUILD="X86" -DPython_ADDITIONAL_VERSIONS=2 -DLLVM_BUILD_MODE=RelWithDebInfo -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLLVM_ENABLE_ASSERTIONS=y -DCMAKE_INSTALL_PREFIX=/scratch/magnus/llvm/11-rc2 -DLLVM_ENABLE_PROJECTS="compiler-rt;clang" -DCMAKE_CXX_STANDARD=14`. I am using Arch Linux.

Here's a GDB backtrace when running `genmc tests/correct/data-structures/mutex/variants/main0.c`
```
#0  0x00007ffff3e74d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff3e5e862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff3e5e747 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff3e6d616 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007ffff49d3873 in llvm::cl::ParseCommandLineOptions(int, char const* const*, llvm::StringRef, llvm::raw_ostream*, char const*, bool) () at /home/magnus/repos/llvm-monorepo/llvm/lib/Support/CommandLine.cpp:325
#5  0x0000555555ae2dfc in setCommandLineOpts(clang::CodeGenOptions const&) ()
    at /home/magnus/repos/llvm-monorepo/llvm/include/llvm/ADT/SmallVector.h:152
#6  0x0000555555afcc52 in (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) ()
    at /home/magnus/repos/llvm-monorepo/clang/lib/CodeGen/BackendUtil.cpp:861
#7  0x0000555555afe867 in clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) () at /usr/include/c++/10.2.0/bits/move.h:76
#8  0x0000555555a943c6 in clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) ()
    at /home/magnus/repos/llvm-monorepo/clang/include/clang/Basic/TargetInfo.h:1066
#9  0x00005555562e1db9 in clang::ParseAST(clang::Sema&, bool, bool) ()
    at /home/magnus/repos/llvm-monorepo/clang/lib/Parse/ParseAST.cpp:171
#10 0x0000555555f7e259 in clang::FrontendAction::Execute() ()
    at /home/magnus/repos/llvm-monorepo/clang/lib/Frontend/FrontendAction.cpp:950
#11 0x0000555555f35d96 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) ()
    at /home/magnus/repos/llvm-monorepo/clang/lib/Frontend/CompilerInstance.cpp:984
#12 0x0000555555989e75 in main (argc=<optimized out>, argv=0x7fffffffe5d8) at /usr/include/c++/11.1.0/bits/unique_ptr.h:407
```

**Comment by michaliskok** [comment]
Thanks for the report, Magnus. This should be OK since a while now, but I forgot to close this.
